# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'
    doctrineSubscribedEvents: []
    indices:
       - name: presentation_bases
         class: App\Entity\PPBase
         enable_serializer_groups: true
         index_if: isSearchable