# All available configuration can be found here:
algolia_search:
  doctrineSubscribedEvents: []
  prefix: '%env(APP_ENV)%_'
  indices:
    - name: presentation_bases
      class: App\Entity\PPBase
      enable_serializer_groups: true
      index_if: isSearchable
