# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    assets:
        base_path: /media/static/images/
        packages:
            icons:
                base_path: /media/static/images/icons/
            pp_edit:
                base_path: /media/static/images/icons/edit_presentation/
            pp_wysiwyg: 
                base_path: /media/static/images/icons/edit_presentation/wysiwyg/
            pp_edition_menu: 
                base_path: /media/static/images/icons/edit_presentation/menu
            pp_consult: 
                base_path: /media/static/images/icons/consult_presentation/
            business_card: 
                base_path: /media/static/images/icons/business_card/
            popular_website_logo: 
                base_path: /media/static/images/icons/popular_websites/
            misc: 
                base_path: /media/static/images/icons/miscellaneous/
            larger: 
                base_path: /media/static/images/larger/
            tutorial: 
                base_path: /media/static/images/larger/tutorials/
                
    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
